services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    command: pnpm run start:dev
    env_file:
      - ./.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
  postgresql:
    image: postgres
    restart: always
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
